version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - symfony
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: ./docker/build/php/Dockerfile
    #command: ["/usr/bin/wait-for-it", "mysql:3306", "--", "bin/console", "doctrine:database:create"]
    command: bash -c "/usr/bin/wait-for-it mysql:3306  -- bin/console doctrine:database:create --if-not-exists && bin/console doctrine:migrations:migrate && apachectl -D FOREGROUND"
    networks:
      - symfony
    volumes:
      - .:/var/www/html
    ports:
      - 8002:80
    environment:
      - DATABASE_URL=mysql://root:12345@mysql:3306/sport?serverVersion=5.7
    depends_on:
      - mysql
networks:
  symfony:
volumes:
  mysql-data: